version: '3'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    restart: on-failure
    container_name: nestjs-api

    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - 80:${APP_PORT}
    
