name: CI/CD pipeline

on:
  push:
  pull_request:
    

jobs:
  test:

    runs-on: ubuntu-latest
    concurrency: test
    environment: test
    strategy:
      fail-fast: true
      matrix: 
        node-version: [16]
    
    steps:
      - uses: actions/checkout@v2
      - name: Using Node.js version ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint,build and test
        run: npm run lint && npm run build && npm run test